### ISSUE TITLE
image-coding regex does not evaulate '\s' correctly

### ISSUE THREAD

**Issue by gjbunyea** [Simon-Initiative/oli-torus#1098]
**Describe the bug**
in regex, a `/s` should be evaluated as any white-space character a space of enter character. 

**To Reproduce**
1. Create image-coding activity
2. Set answer to regex using a `\s`, ex: `7\s17\s8\s18`
3. Enter code that produces the expected, ex: `print(7, 17); print(8, 18)`
4. Run code, see correct result, ex: 
```
7 17
8 18
```
5. Submit
6. NOTICE: Incorrect feedback shown

**Screenshots**
Here's what happens in Torus:
![image](https://user-images.githubusercontent.com/18299544/119893584-8d3b0b80-bf09-11eb-9e1a-908588d77d20.png)

All the following are correct matches for the provided regex
![image](https://user-images.githubusercontent.com/18299544/119892817-98416c00-bf08-11eb-8ce5-6f4ab24b6f13.png)

Description of the `\s` regex:
![image](https://user-images.githubusercontent.com/18299544/119892766-895ab980-bf08-11eb-8dc6-489e40ac10f5.png)

**Environment (please complete the following information):**

**Additional context**
This issue affects some of the questions in the KTH CS101 course: https://proton.oli.cmu.edu/project/kth_swedish_cs101/resource/kodskrivande/activity/lr_genom_att_gra_ce7b1

**Comment by andersweinstein** [comment]
This looks like the same issue as https://github.com/Simon-Initiative/oli-torus/issues/1096

This is caused by matching across lines. Our implementation of the print function simplified things by adding a space after every printed element, rather than only between elements on a line. So each line ends with two space characters, the trailing space and the newline. I suppose this is different than what was used in the original course. As it is now, to match across a line you need `\s\s` or `\s+` (which would allow any amount of space). Or we can change the print function to only print spaces as separators.

**Comment by andersweinstein** [comment]
That is to say, the true bug is that the print function puts an extra space at the end of multi-element output lines This is unexpected by people composing regex's to match exactly across line breaks, so seems worth it to fix the print function.
