### ISSUE TITLE
Code written in image coding activities disappears when you switch to a different page and back

### ISSUE THREAD

**Issue by joecoolle** [Simon-Initiative/oli-torus#1191]
**Describe the bug**
Code written in image coding activities disappears when you switch to a different page and back

**To Reproduce**
1. Go to any page with an image activity, e.g. 'https://proton.oli.cmu.edu/sections/sommarprogrammering/page/bildkod'
2. Add code in the LBD activity'
3. Switch to any other page, and back
4. Your code is now gone.

**Expected behavior**
I expect the code I have written myself should still be on that page.

**Environment (please complete the following information):**
 - OS: macOS 11.4
 - Browser Chrome
 - Version Version 90.0.4430.212

**Comment by gjbunyea** [comment]
Neither unsubmitted nor submitted states of this activity result in persistent code. At minimum, submitted code should persist. This would bring the image-coding in-line with the other activities who also have persistent submissions.

A submitted incorrect answer with added code on line 4 `print("hello")`
![image](https://user-images.githubusercontent.com/18299544/124620064-26cdd500-de47-11eb-95c1-e10afdc026b8.png)

Navigating to a different page and back results in the code-editor being reset, but the "Incorrect" feedback remaining
![image](https://user-images.githubusercontent.com/18299544/124620328-5c72be00-de47-11eb-9c72-b68e2527b805.png)

**Comment by darrensiegel** [comment]
The issue here appears to be that the `ImageCodingDelivery` component only ever looks at the `starter code` attribute to populate the initial state of the code editor.  It does not take into account that previous existing attempt state from the student might exist.  The logic should be:

1. If there is current attempt state (student response) that is not "null" use that for the initial state of the code editor
2. If the current attempt state student response is null, then consider the "starter code". If it is not null, use that.
3. Otherwise use the empty string.
