### ISSUE TITLE
Numeric answers accepts wrong answers

### ISSUE THREAD

**Issue by joecoolle** [Simon-Initiative/oli-torus#1203]
**Describe the bug**
The numeric question type does not seem to compare the value of the input. Questions with an expected correct answer of 5, also accepts 50, 500, etc.

**To Reproduce**
1. Go to 'https://proton.oli.cmu.edu/authoring/project/kth_swedish_cs101/resource/kilobyte_megabyte_och_gigabyte/activity/oli_short_answer_1jw8l'
2. Run the question
3. Enter e.g. 50 as answer and click submit
4. Se the (incorrect) feedback för a correct answer.

**Expected behavior**
Only the correct answer should be graded as correct.

**Screenshots**
![image](https://user-images.githubusercontent.com/53688217/123510433-cd61eb00-d67b-11eb-85af-a3d44f4a5cba.png)

**Environment (please complete the following information):**
 - OS: macOS 11.4
 - Browser Chrome
 - Version Version 90.0.4430.212

**Comment by darrensiegel** [comment]
The issue is related to ingestion.  It did not  explicitly set the inputType to be "text", and thus Torus assumes, by default, that it is a Numeric.

But the rules for that activity were defined with the intent on it being a Text question - so they used the "like" operator, instead of the "=" operator

This can be worked around and fixed for this question by simply toggling from "Numeric" back to "Text" and then back to "Numeric"

**Comment by joecoolle** [comment]
Thank you! That leads me to the idea that it would be great to be able to use conditionals to formulate more advanced feedback (e.g. >, <,  && etc., but I'll make a improvement suggestion for that.
