### ISSUE TITLE
Publication tracks removed activites if they are quickly removed: CMU-302

### ISSUE THREAD

**Issue by eliknebel** [Simon-Initiative/oli-torus#1340]
**Describe the bug**
Adding an activity then quickly removing it before the page can finish saving causes the publication to continue to track the activity, and can be see in the publication changes.

**To Reproduce**
1. Go to an authoring page
2. Add a multiple choice then quickly delete it before the page finishes saving
3. Go to the Publish page and see the multiple choice is in the set of changes 

**Expected behavior**
A publication should not track any activities that have been deleted. A short term fix is to disable the delete button until the page save is complete, then allow deletion if necessary. A better more user friendly fix would be to allow immediate deletion but handle it correctly.

**Screenshots**
<img width="915" alt="Screen Shot 2021-07-30 at 4 35 56 PM" src="https://user-images.githubusercontent.com/6248894/127709345-3e7eb5cd-366a-48ff-954a-85401e196533.png">
<img width="1212" alt="Screen Shot 2021-07-30 at 4 35 46 PM" src="https://user-images.githubusercontent.com/6248894/127709346-c5b24a61-ce8e-43e1-bd1a-5846682ac4dc.png">

**Environment (please complete the following information):**
 - OS: macOS 11.4
 - Browser: Safari
 - Version: 14.1.1

**Comment by LEDThereBeLight** [comment]
Why is this happening -> are changes not being synchronized correctly? Should not show on pub page.

**Comment by LEDThereBeLight** [comment]
The issue here is that adding an activity immediately calls a "creation" persistence method to create the resource/revision, then the call to update the page with the attached activity reference is deferred until the timeout is completed. However, if you remove the activity before the save time expires, when the save propagates then the page editor server code does a diff of the old/new activity references, sees there are none, and does not follow the normal logic path of marking the activity revision as deleted. so since it's not deleted, it shows up on the publications page.
