### ISSUE TITLE
Submit should not be necessary for every single question type

### ISSUE THREAD

**Issue by czerwinskie** [Simon-Initiative/oli-torus#1584]
**Describe the bug**
It is very cumbersome, and limits attempts by students, to require a submit for every question.  This is done much better in Torus legacy...to only have a submit for questions types that require it, like multiple-select.

**Comment by LEDThereBeLight** [comment]
Assuming this is for formative/ungraded pages (summative/graded pages should only have one submit button) --

Current activity types:
- Short answer
- Multiple Choice
- Check all that apply
- Ordering
- Multi-input
- Image Coding

If I'm understanding this right, of these activities, only multiple choice can be submitted after a student selects an option. I agree, immediately submitting the activity and showing feedback feels more responsive, but it would also deviate from the behavior of every other activity type. Because of that, I think, personally, keeping the activities consistent and always requiring a student to click the submit button is probably the right approach.

**Comment by eliknebel** [comment]
Per triage, we will shift our approach to submit automatically for the activities that will support it, e.g. MCQ
