### ISSUE TITLE
Hints appearing when text not given.: CMU-438

### ISSUE THREAD

**Issue by ctipperCMU** [Simon-Initiative/oli-torus#1835]
**Describe the bug**
In the Preview, some of the activities offer Hints even though no hint text is given. Initially I thought it was activity-type-specific, but I have two multiple choice questions and one has the problem while the other doesn't. 

**To Reproduce**
1. Go to 'Reacting to Errors Module' project Preview
2. Click on 'Pre-instruction' page
3. Scroll down to Question 3 and Question 5
4. See difference: Q3 does not have Hints block (desired behavior) while Q5 does.

**Expected behavior**
Any activity without text in the Hints definition should not display the Hints block. Note: this project has not yet been published so the issue (at this point) is with Preview.

**Screenshots**

<img width="734" alt="Screen Shot 2021-11-09 at 2 00 34 PM" src="https://user-images.githubusercontent.com/15051511/140987548-50b63df9-7a72-432e-b122-6a36350942b1.png">
<img width="753" alt="Screen Shot 2021-11-09 at 2 00 42 PM" src="https://user-images.githubusercontent.com/15051511/140987565-21ed51a2-53f6-40e6-a4df-7d773b04284e.png">

**Environment (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 95.0.4638.54

**Additional context**
Preview link for a page with this issue: [https://proton.oli.cmu.edu/authoring/project/formative_assessment/preview/preinstruction](https://proton.oli.cmu.edu/authoring/project/formative_assessment/preview/preinstruction)

**Comment by normanbier** [comment]
Some additional information: this is also related to Single-Response when created as Short Text or Numeric (paragraph doesn’t have the same issue).  These question types always have three empty hints associated with them (I’m assuming that these are being created in someway at the time the question is created).  Changing the type (from Short Text to Paragraph, for example) doesn’t change the existence of rendered hints.  Changing a paragraph to Short Text does NOT add hints, however (which is why I’m assuming this is happening at the time the question is first created). Note that the authoring interface does not seem to reflect the existence of these hints.



A related issue (maybe filed separately or maybe this can be addressed at the same time.  Even if you intentionally create a hint, there’s no way to later remove it (deleting the text still leaves a blank hint).

**Comment by gjbunyea** [comment]
+1 
Questions with out any hint text still present the Hint buttons. Clicking the Hint button in this scenario results in a blank hint shown.

![image](https://user-images.githubusercontent.com/18299544/148998089-2f3af3a1-08b2-4a37-a753-17733f8656ad.png)

**Comment by czerwinskie** [comment]
This is being reported as a blocker for PL2 folks who are developing a pilot course to share widely and Eberly folks who are also actively developing.  It also looks really bad in a demo.
