### ISSUE TITLE
Students should be able to pay or apply codes during grace period: CMU-417

### ISSUE THREAD

**Issue by darrensiegel** [Simon-Initiative/oli-torus#2003]
Currently when a student is accessing a paid course section that has a grace period, there is no way for the student to make a direct payment or to apply a code during that grace period. 

Furthermore, there is no indication to the student that there is even a grace period in effect.  

Torus needs some student facing mechanism to allow that visibiility and the ability to make payments and apply codes.

**Comment by ehilfer** [comment]
Doug Sonaty commented: [~accountid:557058:e9d56545-b28f-41b6-b9bf-83b2efb83707] I am seeing the following issue:

# Log into [https://moodle.opensimon.unicon.net/|https://moodle.opensimon.unicon.net/|smart-link] with dougstudent1 / Testing123\!
# Click on the ‘04/05 Paid Course with Grace’ course.
# Click on the ‘04/05 Paid Course with Grace’ LMS LTI link. NOTE: The following is listed: You have 20 more days remaining in your grace period access of this course Pay Now
# Click on the ‘Pay Now’ link.

Expected behavior: I have an option to pay with either a credit card or code.

Actual behavior: I only have the option to pay with a credit card.
