### ISSUE TITLE
Hide Advanced Activities, enable Multi-Input across all projects

### ISSUE THREAD

**Issue by gjbunyea** [Simon-Initiative/oli-torus#2632]
**Is your feature request related to a problem? Please describe.**
Advance Activities appear as an option for all course projects. These should likely be hidden, with key activities enabled across the whole system. Multi-Input for example should be system-wide. 

Image Coding and Adaptive Activity are highly specialized and should either be hidden or provide guidance on when appropriate to use. 

OLI Embedded as far as I understand is a 'behind the scenes' or power-user activity that shouldn't be used by any given course author. 

![image](https://user-images.githubusercontent.com/18299544/172449731-1b783e58-fc47-4687-9cfc-67828c9a1b3b.png)

**Comment by eliknebel** [comment]
Multi input should be considered a basic activity that is enabled by default.

Other refactoring of how to present these options may be necessary, possibly just adding a sentence to describe the activity. We should also consider adding a "categorization" field to these activities so that they can be filtered based on specific needs of the course/author. Adaptive activity may not even belong in this list at all.

**Comment by gitnauk** [comment]
Tested 6/27/22 ❌

I started a new project and these Advanced Activities are showing up as options, including Multi Input. 
Multi Input does not seem to be a system-wide default yet



![Image](https://user-images.githubusercontent.com/41222927/176008731-375eb38b-04cd-4ce6-ad89-2b4bef21813a.png)
