### ISSUE TITLE
Allow multiple lines in formula blocks using "line breaks” with backslashes (\) with LaTex

### ISSUE THREAD

**Issue by eliknebel** [Simon-Initiative/oli-torus#2884]
Math course authors want the ability to create “line breaks” within the equations by using backslashes (\) with LaTex. This would allow multiple lines of formulas in one block of math editor.

**Comment by marc-hughes** [comment]
According to https://github.com/mathjax/MathJax/issues/2312

New lines are not currently supported in MathJax 3 (weird, right?)
Supposedly, it's under development for a release with a timeframe of "end of this summer"

We have three options:

1. Wait until that release
2. Work-around that by parsing out newlines and then rendering two different mathjax formulas within a single block so it is visually on two lines
3. Authors can use the \displaylines{} command something like this:

![image](https://user-images.githubusercontent.com/333265/184188095-1546a951-3573-46a6-9fb0-67344f45af68.png)


If we went with 2. for the short-term, we could go back to 1. when its ready, and I don't think it would be more than a day or two's work to do that, but considering 3. works today, I'm unsure if it's worth doing.  @eliknebel or @darrensiegel - Got a suggestion on a direction there?

**Comment by andersweinstein** [comment]
Would it be even easier than 2. if torus just inserted a step to rewrite `\\`-containing LaTeX payloads to` \displaylines{..}` form before rendering?

**Comment by andersweinstein** [comment]
It turns out there are a LOT of instances of this in Chem1 and Chem2. It is used pervasively in those courses to show derivations in question feedback and explanations. Grep finds about 20,000 `\\`'s in 287 files in legacy Chem1 XML source. Many equations have multiple occurrences so there are fewer _equations_ than that. And a small number are only at the end of the equation so may not need to be handled. But it is too many to easily fix by manual editing and a very high priority issue for courses that have already migrated to torus.
