### ISSUE TITLE
Torus: long equations extend off the page to the right

### ISSUE THREAD

**Issue by strader** [Simon-Initiative/oli-torus#3641]
**Describe the bug**
Due to styling differences, complex equations that used to fit on the page on legacy now extend off the page to the right.

**To Reproduce**
Example on legacy: https://dev-03.oli.cmu.edu/jcourse/workbook/activity/page?context=4eb2acac7f000001671ece68759b3bcb

Example on Torus: https://proton.oli.cmu.edu/sections/gen_chem_0427_default_org_4gfjy/page/8i2pe_mole_conversions_multistep_hjdwn

Scroll down to first equation starting with 0.0400.

**Screenshots**
Legacy on left, Torus on right:

![Screenshot from 2023-06-06 15-46-01](https://github.com/Simon-Initiative/oli-torus/assets/2669407/7f857e03-340f-414a-a88b-2c0b0da26034)

**Comment by eliknebel** [comment]
https://eliterate.atlassian.net/browse/MER-2131

**Comment by normanbier** [comment]
I'm re-reviewing this, and realizing that the long equation issue keeps coming up in part because the equation font is much larger in Torus than on legacy, and so it's happening a lot more frequently in Torus than it is in legacy. I'd like to reduce equation front size, which still leaves readable text for equations but will dramatically reduce cases of equations off screen.

I would also like to add this back into the v24 fixes.

**Comment by marc-hughes** [comment]
Originally, the formulas were set to a 1 REM font size.
On June 27, I had lowered it to 0.8, which fixed most of these issues.
This particular formula is quite long, so I'm going to further reduce the font size to 0.7REM

![image](https://github.com/Simon-Initiative/oli-torus/assets/333265/0d05abb3-d45b-4c4c-8b1f-0273cb7d22c4)
