### ISSUE TITLE
[Stellarator] Instructor Dashboard: Quiz names absent in Quiz Scores sub-tab 

### ISSUE THREAD

**Issue by tanvidomadia** [Simon-Initiative/oli-torus#3829]
**Description of the bug**
The quiz names are absent in the Quiz scores sub-tab in the Instructor Dashboard

**To Reproduce**
1. Go to a course section on stellarator.oli.cmu.edu as an instructor
2. Click on the Reports tab
3. Scroll down and click on the Quiz Scores sub-tab
4. The names of the students appear without the quiz scores or quiz names

**Expected behavior**
![Firefox_Screenshot_2023-07-05T18-58-17 206Z](https://github.com/Simon-Initiative/oli-torus/assets/20156664/bacba94f-fa99-4390-93c0-9e33e82b3c78)

**Environment (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by darrensiegel** [comment]
I don't see what the problem is. 

I've looked at this on both Stellarator and locally running the prelease v24 branch.  I see the graded page titles.  For instance:

![Screenshot 2023-07-05 at 3 06 04 PM](https://github.com/Simon-Initiative/oli-torus/assets/7431756/53e700a9-9c94-48ff-b68a-1ea0645f4707)

Can you share a screen shot of where you are *not* seeing the graded page titles appearing as column headers?

**Comment by tanvidomadia** [comment]
Here's the screenshot I am seeing in a Gen Chem project: 

![stellarator-ld3](https://github.com/Simon-Initiative/oli-torus/assets/20156664/c9fa2a0d-f087-441f-8149-f2367c23c42f)


**Links**
[Stellarator Instructor View](https://stellarator.oli.cmu.edu/sections/test_general_chem_630/instructor_dashboard/reports/quiz_scores)
[Stellarator Instructor Section](https://stellarator.oli.cmu.edu/sections/test_general_chem_630/instructor_dashboard/overview)
[Stellarator Base Authoring Project](https://stellarator.oli.cmu.edu/authoring/project/general_chemistry_i_bnbnt/overview)

**Comment by darrensiegel** [comment]
The issue here is that Quiz Scores is not displaying Unordered pages.  Captured with another instance here: https://eliterate.atlassian.net/browse/MER-2237
