### ISSUE TITLE
Student progress is broken

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#3895]
On Stellarator, when a student works through a course the progress percentage never changes from 1%.

Try this course as a student:
https://stellarator.oli.cmu.edu/sections/demo__rise_analysis/enroll

https://github.com/Simon-Initiative/oli-torus/assets/24977416/7cf0e5b8-692c-4d13-94b8-07ed07bd65fb

**Comment by eliknebel** [comment]
Related to https://github.com/Simon-Initiative/oli-torus/issues/3880

**Comment by darrensiegel** [comment]
The issue here is that this section was an "existing" section that had v24 ContainPage infrastructure introduced into it.  

The ContainedPage schema only gets updated in a section at section creation time and during Remix. 

I'm not inclined at this point in the v24 dev cycle to add in a way to detect that this needs to be done and run in JIT, given that there will be likely few sections actually in use that this will affect.  All Fall courses, all LL courses will be created anew after the release. 

For those that are affected, the workaround is simply to go into Remix, make any change, then Save.  ContainedPage infra is updated and progress works.
