### ISSUE TITLE
Issue with LBD grading and feedback in [LATEST] REAL Chemistry I (Taylor's Version) { ingested July 20 -nbier}

### ISSUE THREAD

**Issue by markblaser** [Simon-Initiative/oli-torus#4017]
**Describe the bug**
In Unit 3, Module 10, The Particle Nature of Light
Correct answer in PhotonEnergyLBD2 is graded as incorrect. 

**To Reproduce**
1. Go to 'https://proton.oli.cmu.edu/authoring/project/real_chemistry_i_taylors_versi/preview/the_particle_nature_of_light'
3. Scroll down to 'LBD starting with "Photons of infrared radiation are responsible for..." '
4. Enter correct answer (1.6e23) and see errors in grading, feedback and hints (screenshots below).

**Expected behavior**
That answer (range of 1.6e23 to 1.62e23) should be graded as correct and correct setup and solution answer should show.
Note: it does work correctly if I set it for exact answer.
Also: There are only two hints, but three hints are shown (the first hint is duplicated).

**Screenshots**
<img width="579" alt="PhotonEnergyLBD2" src="https://github.com/Simon-Initiative/oli-torus/assets/140570797/cb8fa7bc-f17f-46c2-ad90-dcc15a39d129">
<img width="922" alt="error 1" src="https://github.com/Simon-Initiative/oli-torus/assets/140570797/ecf238d9-bc2f-4f43-b53c-42f98b1598d3">
<img width="720" alt="Hints" src="https://github.com/Simon-Initiative/oli-torus/assets/140570797/af973ef1-944b-4c77-93cc-e183668da04d">
<img width="920" alt="duplicate hints" src="https://github.com/Simon-Initiative/oli-torus/assets/140570797/4ce8e72e-76b7-4edf-94fd-a5b37b3c2c65">

**Environment (please complete the following information):**
 - OS: [Ventura 13.0]
 - Browser: [Chrome]
 - Version: [Version 112.0.5615.137 (Official Build) (arm64)]

**Additional context**
https://proton.oli.cmu.edu/authoring/project/real_chemistry_i_taylors_versi/preview/the_particle_nature_of_light

**Comment by normanbier** [comment]
There are two issues captured here -- one about hints, one about correct answers. I'm splitting these. Hints is a real bug, I'm going to recapture it in a separate ticket. The repetition of hints only occurs when you "reset" the question -- the original hints never go away and you can request a second set of hints on reset so the list keeps growing and repeating. HOWEVER it only seems to occur in author preview, I could not replicate in student view. See: https://github.com/Simon-Initiative/oli-torus/issues/4018

Regarding the answers bug:
This seems to be an issue with specifying positive exponents as part of the answer.

Note that the question that is referenced has two parts -- the first question expects a negative exponent in the answer key, and is behaving as expected.  The problem seems to be in the notation used in the answer key in a range. If you specify an answer that explicitly specifies the + signi.e. 1.6e+23 to 1.7e+23, then nothing the student enters will be correct except an exact match..  However, if you omit the plus sign in the answer key) (1.6e23 to 1.7e23) then a student can answer with or without (1.62e+23 OR 1.62e23).  I do not know if this is an answer only in range or if it is any numeric input involving exponents.

@markblaser I modified your question to not use the + notation, as you'll see. Can you verify that this works as expected from the student perspective?

@darrensiegel can you consult with @markblaser on how big a deal this is? Given that it works correctly from the student end, we may be able to live with it. But if it requires authors going in and removing the plus sign from positive exponents in a large number of questions, it may be a higher priority.

**Comment by markblaser** [comment]
Thanks Norm!
1. My recollection is trying both +23 and 23 and getting the error either
way (but I'm not certain).
2. I only checked in preview mode.
3. Not sure if I have a student account. Thought Kim was going to (or did)
give me access as a student but if so I can't find it. Can you please add
me to the course as a student?
4. Kim set up an instructor account for me (
***@***.***) which (I think) used to have some
classes and now does not.
