### ISSUE TITLE
Threaded Discussions, show additional details, allow "most recent post" vs "most recent reply"

### ISSUE THREAD

**Issue by adanbar** [Simon-Initiative/oli-torus#4073]
In the discussions overview section, accessed from the nav bar, all posts are arranged in one level. There is no threading. As a result, this view will be quickly impractical in real world use, even with only dozens of students posting once or twice a day. A single highly active thread on a single page may even overwhelm.

What's needed is a threaded system in which at a minimum each pages posts are in one thread. Better to have every post start a new thread (maybe use an LLM to suggest a thread title).

![image](https://github.com/Simon-Initiative/oli-torus/assets/141290940/beb37efc-51ec-439e-93b2-7ccd5903bec3)

**Comment by darrensiegel** [comment]
The intent for this view for the student is to provide a summary of recent discussion activity, showing them only the top level post, but allowing them to then click on a post to go to the page where it was made in order to see the post in context (with all of its replies).  The view shows a list of the five most recent posts that the current student has made, and the five most recent posts made by all students.  The post listings here do not render replies, so there won't be the issue of threaded discussions overloading the view. 

But what I do think is missing is some indication as to recent activity related to each post.  It would be helpful to display the number of replies and perhaps the date/time of the latest reply for each post.  

In addition, many other discussion forum systems offer a feature to allow the user to switch between viewing threads either with "most recent post" or "most recent reply".  The former is what this view offers currently, where I as a student can easily see the newest posts.  But perhaps more useful is the ability to see the top-level posts that have the most recent replies, allowing the user to find easily the "active" threads - even when the top-level post is old.
