### ISSUE TITLE
System doesn't recognize when new account creation uses email from existing account

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#4093]
I created a new learner/instructor account with an email address I'd previously used.
The system let me proceed and displayed the notification language for confirming my email address.
The email never arrived and there was no hint that the email was already associated with an account.

Preferred behavior: interface notifies user that the email is in use, and prompts them to retrieve their password or try a different email address for a new account.

**Comment by eliknebel** [comment]
This is a security feature of the system, unfortunately with the downside that it results in a poor experience for users who forget they already have an account.

The system should not indicate that an account with a particular email already exists in order to prevent enumeration attacks.
https://hexdocs.pm/pow/security_practices.html#user-enumeration-attacks

Though, it might be helpful to actually send an email along the lines of "Someone attempted to create a new account with this email. If this was you, you can login or reset your password here..."

**Comment by eliknebel** [comment]
The system should send an email along the lines of "Someone attempted to create a new account with this email. If this was you, you can login or reset your password here..."
