### ISSUE TITLE
Section enrollments view should show 'suspended' enrollments and allow re-enrollment

### ISSUE THREAD

**Issue by bitbldr** [Simon-Initiative/oli-torus#4193]
"Manage Enrolled Students" view should allow the option of displaying 'suspended' enrollments and allow re-enrollment. Having a filter on this view that is a checkbox "Show all enrollments" is likely needed.

**Comment by kwahlenmayer** [comment]
Instructors should not be able to unenroll lti students (really any students). 

Suspend, instead of unenroll, at least shows the history of the enrollment and can be reversed. 

If an LTI student follows a link to an enrollment in which they were suspended, at least the student message would be you are suspended instead of Not Authorized.

**Comment by bitbldr** [comment]
Closing as duplicate
