### ISSUE TITLE
Student's reviews of scored assessments are improperly labeled

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#4209]
**Describe the bug**
No matter what attempt a student is reviewing, it's listed as Attempt No.1
The attempt itself lists multiple timestamps -- Started, Submitted, and each question's Evaluation. The Start and Submitted timestamps are in the local time; the Evaluated timestamp is in UTC

**To Reproduce**
Visit a student's second or third attempt, and note the questions all say "Attempt No.1"
Also note the timestamp and compare the question to the Started/Submitted times.

**Expected behavior**
The Attempt will be correctly labeled.
The timestamps will all match on time zone. UTC is not useful for users.

**Screenshots**
<img width="1608" alt="Screenshot 2023-09-14 at 1 37 34 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/24977416/7a162f2f-d4ae-4d57-8b03-f31b29953f13">

**Environment (please complete the following information):**
All

**Additional context**
N/A

**Comment by bitbldr** [comment]
@halturner can you add a link to the issue?

**Comment by halturner** [comment]
@bitbldr https://proton.oli.cmu.edu/sections/hals_spanish_test_course/page/leccin_2_quiz_60ema

This is attempt #3
https://proton.oli.cmu.edu/sections/hals_spanish_test_course/page/leccin_2_quiz_60ema/attempt/f848e339-e687-4e39-9f81-d024eb6ae9a0/review

**Comment by bitbldr** [comment]
The core of the issue is that activities on scored pages will only ever have a single attempt, since the attempt numbers are incremented at the page level. This is caused by reusing the same infra from unscored pages here.

We should somehow indicate which page attempt a student is actually viewing, perhaps removing/special casing to remove the activity attempt number for scored pages
