### ISSUE TITLE
Error when authoring a pool question

### ISSUE THREAD

**Issue by sandyraysor** [Simon-Initiative/oli-torus#4299]
When trying to edit this question (image) I keep getting this error message and I can't fix it.

![image](https://github.com/Simon-Initiative/oli-torus/assets/36045601/ab991071-41bc-4c26-919b-a1e129dd37b5)

https://proton.oli.cmu.edu/authoring/project/real_chemistry_i_taylors_versi/bank

**Comment by andersweinstein** [comment]
Was able to repair this question so that it is editable. Treated answer "True" to part 3 as correct based on feedback. Change is not published. 

It appears this question came out at time of migration with a correct targeted feedback response for response "True", which is still there, but the default response for choice "True" had feedback "Incorrect" and score of zero.

**Comment by bitbldr** [comment]
Repaired manually in the JSON
