### ISSUE TITLE
(Migration) Red MathML text does not render as red on tokamak

### ISSUE THREAD

**Issue by cjlim1092** [Simon-Initiative/oli-torus#4387]
**Describe the bug**

[SVN](https://svn.oli.cmu.edu/svn/community/stem/fast_track/branches/v_1_1-echo/content/Unit_mathematics/m5_signed_values/x-oli-workbook_page/signed_values_3.xml)
[Echo](https://echo.oli.cmu.edu/#fast_track-1.1/signed_values_3?organization=fast_track-1.1_default)
[Legacy](https://oli.cmu.edu/jcourse/workbook/activity/page?context=8c1e045d0a0001dc411577ad0ff729f5)
<img width="690" alt="image" src="https://github.com/Simon-Initiative/oli-torus/assets/32859465/b7a78017-71d2-4448-bb6f-8b017f1ce2c1">
[Tokamak](https://tokamak.oli.cmu.edu/sections/stem_foundations_102023/page/urlgr_order_of_operations_q1dwn)
<img width="690" alt="image" src="https://github.com/Simon-Initiative/oli-torus/assets/32859465/5eb7e280-3cc2-4f26-b7ae-b71b21da6c47">

**Environment (please complete the following information):**
 - Version: 26

**Additional context**
High Priority course for India project

**Comment by bitbldr** [comment]
This is a mathjax issue, it may be related to the version mismatch between legacy and torus.

**Comment by andersweinstein** [comment]
Looks like torus' newer version of MathJax wants one to put all styling as css in the style attribute e.g. `style='color:red'` for red color, or, for both bold and red, `style='fontweight=bold;color:red'`. This fix might be made in the XML source, or fixed in torus authoring (though editing MathML in torus is painful.)

(While experimenting, I made this change in the authoring project for above course on tokamak, but have not published the change. However, if there are expected to be further ingestions, the change should be made in the SVN source.)

In theory migration tool could peek into MathML and try to make adjustments like this for obvious cases like color attributes. But if it is only going to affect a very small number of cases, this is not worth the effort.

**Comment by andersweinstein** [comment]
A simpler change is to rename the `color` attribute to `mathcolor `wherever it occurs within a mathml element. For example, where you see `<m:mn style='bold' color='red'>` change it to `<m:mn style='bold' mathcolor='red'>`
