### ISSUE TITLE
(Migration) Content element type 'figure' is not supported

### ISSUE THREAD

**Issue by halturner** [Simon-Initiative/oli-torus#4405]
**Describe the bug**
Figures do not migrate.

**To Reproduce**
https://tokamak.oli.cmu.edu/sections/systematic_reviews_and_metaana/page/i43sj_wellformulated_review_question_nxxjd
Search for "Content element type 'figure' is not supported. Please contact support with issue #RFDKS8PEMGKVW9JQUHSRQU"

**Expected behavior**
Figures to be migrated and displayed.

**Screenshots**
<img width="1061" alt="Screenshot 2023-11-07 at 1 56 29 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/24977416/22eddc24-b031-4609-aa29-1f78c1d94177">
<img width="934" alt="Screenshot 2023-11-07 at 1 56 40 PM" src="https://github.com/Simon-Initiative/oli-torus/assets/24977416/32320a79-a799-4ba7-8213-bf0cc9396254">

**Comment by bitbldr** [comment]
We should decide whether we actually need to support figures on torus or not, then determine if they should be migrated

**Comment by bitbldr** [comment]
@drva will look into some accessibility considerations for the figure element

**Comment by andersweinstein** [comment]
The example is an untitled figure box element whose content consists of an image with caption. The caption in this case has some complex content (text and a link to the source).  The migrated figure renders in authoring, showing the image only, but causes this error in preview/delivery. Experiment shows that adding a title to the figure element in authoring removes the problem. Even entering a title then changing it to empty fixes the problem. The issue therefore seems to be migration producing a figure box without a title element. 

However, there is also ANOTHER issue: the image's caption is not being rendered in either authoring or preview/delivery in this case. It does appear the original image/caption content is migrating into the caption property of the image and getting correctly wrapped in a paragraph.

In general, it does not appear to be necessary to wrap this image in a figure at all, since there is no title for it and a caption  is already included with the image. So one workaround might be to delete the figure wrapper.

**Comment by andersweinstein** [comment]
Caption not showing likely because images are styled as inline, so migrating to torus inline images which don't show captions.

**Comment by bitbldr** [comment]
https://github.com/Simon-Initiative/course-digest/pull/220
