### ISSUE TITLE
Keeping solutions away from the client during exams

### ISSUE THREAD

**Issue by fkohrt** [Simon-Initiative/oli-torus#805]
**Is your feature request related to a problem? Please describe.**

When I was test driving Torus assessments I noticed that answers are sent together with the questions to the browser. Obviously there are limits to anti-cheating measures in online exams, but not making the solutions available during the assessment might be a significant enhancement. Also in order to convince stakeholders to use the Torus platform.

**Describe the solution you'd like**

I am not sure why solutions are sent to browsers in the first place, but maybe do some kind of backend evaluation instead.

**Describe alternatives you've considered**

Locking down the browser and/or proctoring in person.

**Additional context**

Similar issues have been discussed for SCORM, e.g. see the blog post "[SCORM Vulnerabilities + IMS Spec withdrawal = Excitement](https://web.archive.org/web/20120207083455/http://mobilemind.net/2009/04/scorm-vulnerabilities-ims-spec-withdrawal-excitement/)".

**Comment by darrensiegel** [comment]
It is important to note that Torus has broadly two different modes of operation, or two different "feature sets":
1) Authoring mode - This is the editing mode where one or more users can edit pages and activities (including testing out their authored activities) of a course.  After a course is authored, it can be "deployed" and made available for access in:
2) Delivery mode - This is the instructor and student facing experience, launched from an LMS via LTI 1.3

When you stated that you were "test driving Torus assessments I noticed that answers are sent together with the questions to the browser", I suspect that you were exercising questions in the page authoring view, and not actually launching into a deployed course via an LMS?

If that is true, then what you are seeing is expected behavior.  In authoring mode, Torus must provide the full content of questions (including all hints, all feedback, and the correct answer) to the client-side authoring code.  In our delivery mode, these question models are pruned on the server prior to being made available to the client-side delivery code.  This allows the removal of hints, feedback and the correct answer.

**Comment by fkohrt** [comment]
I actually was using delivery mode, but it turns out I can't reproduce this anymore – I have been testing this some weeks ago, but maybe I got something wrong. Sorry for the noise, will close this :)
