### ISSUE TITLE
Open and Free section support

### ISSUE THREAD

**Issue by darrensiegel** [Simon-Initiative/oli-torus#810]
Full details, requirements and approach TBD, but essentials are:
1. Admin determines a course is to be "Open and Free" enabled.
2. A single, canonical hyperlink is then made available to allow direct access (not an LTI launch) to the course, in delivery mode.
3. An anonymous user is created to track that usage, persisting with a cookie, and a unique URL (accessible from the UI to the anon user)

**Implementation Approach**:
- [x] Create admin-only interface in course authoring that can be used to create and manage open and free sections. Show a section specific URL that can be accessed publicly (outside of an LMS) by students to enroll in the Open and Free section anonymously.
      - O&F sections will automatically track the latest publication, same as how regular sections do
- [x] Create routes for O&F section access/enrollment
- [x] Create simple student facing O&F delivery interface which can be accessed by a user outside of LTI context.
- [x] Generate and display an access URL with user-specific token which can be used to authenticate a user and set the session cookie
- [x] Remove all uses of LTI params except for in certain necessary modules (lti_controller and delivery_controller) and replace with section in assigns
- [x] Follow-up on migration `add_if_not_exists`
- [x] Add captcha for accessing open and free
- [x] Start/End date enforcement
- [x] Add ability to toggle a section open_registration so that new enrollments can be enabled/disabled, implement logic to abide
- [x] Improve Project selection drop down. Currently only descriptions, not titles are searchable
- [x] ~~Investigate long term cookie, persistent through browser restarts for user session~~
- [x] ~~Use separate login_token field different from sub~~
- [x] Discuss changing login token approach to email magic link/email & password

**Comment by normanbier** [comment]
We should also support the ability for someone to create an account that can enroll in the O&F sections - we need to have anonymity available but we also want to support account based access so that O&F users can have persistence across sessions? Or are you imagining that cookie-based persistence is enough to cover this use case?

**Comment by bitbldr** [comment]
Yes, that is the current plan of approach. We will create an anonymous user in the system to track usage and a cookie will be set to track session from the browser. The user will also be presented with a user-specific url that they can bookmark to access their session from any device in the future. This user specific url will contain a token and serve the purpose of "user authentication" without requiring the user to explicitly create an account using an email or social login. The upside to this approach is that users remain anonomous and O&F access is trivialy easy, the downside is the user must manage and keep track of their url to access their session and course progress. If the url is lost, then user progress cannot be recovered and a new account must be made. We're assuming this tradeoff is acceptable since these courses are open and free and relatively low stakes
