### ISSUE TITLE
Feedback is not shown for CATA activity

### ISSUE THREAD

**Issue by eliknebel** [Simon-Initiative/oli-torus#912]
**Describe the bug**
Feedback is not shown for CATA activity in a graded assessment.

![image](https://user-images.githubusercontent.com/6248894/113909480-b8c13580-97a5-11eb-8752-4b738332b61b.png)

We should also investigate adding some unit tests for all these client activities so that we have a higher level of confidence in them working as expected.

**Comment by gjbunyea** [comment]
I notice that feedback isn't being given for MCQs on **Tokamak**. Feedback should show up immediately since there's no "Submit" button

It _seems_ OK on production, but wonder if the bug is related?

![image](https://user-images.githubusercontent.com/18299544/114462932-bbf75f80-9bb1-11eb-8b7d-b15a2a1f7a5f.png)

**Comment by eliknebel** [comment]
Good catch @gjbunyea. This must be a regression since tokamak is running the latest and its not an issue on production.
